project:
  type: website

# -- Optional additions ------------------------------------------------------

# execute:
#   freeze: auto

website:
  title: "Choropleth maps in Streamlit"
  description: "A report"
  site-url: https://bainmatt.github.io/streamlit-geomaps/
  repo-url: https://github.com/bainmatt/streamlit-geomaps
  open-graph: true
  search: false
  navbar:
    title: false
    left:
      - href: notebooks/report.ipynb
        text: "Report"
  page-footer:
    center:
      - href: https://bainmatt.github.io/
        text: bainmatt.github.io

format:
  html:
    theme: ember
